#
#                     Ampoliros Application Server
#
#                       http://www.ampoliros.com
#
#
#
# This file is automatically generated by configure script.
# Edit it if you don't want to use configure script.

AMP_HOST=localhost
ROOTCRONTAB=/var/spool/cron/root
PRIVATEDIR=/var/www/ampoliros
PUBLICDIR=/var/www/html/ampoliros
AMP_URL=http://localhost/ampoliros
AMP_ROOTURL=http://localhost/ampoliros/root
AMP_ADMINURL=http://localhost/ampoliros/admin
AMP_CGIURL=/ampcgi/
SITESDIR=/var/www/html/ampsites
HTTPDUSER=apache
HTTPDGROUP=apache
